### ISSUE TITLE
Long/eternal connection.

### ISSUE THREAD

**Issue by ValkyrianAlt** [space-wizards/SS14.Launcher#109]
loading the “connection” takes a long time, either you have to wait a very long time or it doesn’t start at all, even if were able to connection in; When I arrived at the station the game stupidly freezes. This never happened before, and I don’t have any problems with the Internet. Help.

**Comment by metalgearsloth** [comment]
Ask for help on the discord as it's not a launcher issue.

**Comment by ValkyrianAlt** [comment]
> Ask for help on the discord as it's not a launcher issue.

Okay, thanks.
