### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by zetrez** [space-wizards/SS14.Launcher#114]
When I try to log in to the server I always play on, the launcher gives me this:

> _There was an error while downloading server content. Please ask on Discord for support if the problem persists._

I have looked through many forums, but I have not found an effective solution anywhere. I saw a guy here with the same problem, they helped him when he sent the logs, so if you understand how to solve this problem, please help

**Comment by metalgearsloth** [comment]
Ask for help on the discord https://discord.gg/ss14

**Comment by zetrez** [comment]
the solution was super simple, VPN helped me
