### ISSUE TITLE
Trans protection texts in content downloading should be turnable in settings

### ISSUE THREAD

**Issue by Xeno4** [space-wizards/SS14.Launcher#148]
I dont really know why it's so necessary to add this without a possibility to turn it off, considering that some countries list LGBTQ as a terrorist organization(including the country i live in, sadly.)
i'd rather not get SS14 blocked in my country for such a small thing, so please can you add the option to turn that off 🙏

**Comment by metalgearsloth** [comment]
kowtowing to bigots lets em win.

**Comment by FrauZj** [comment]
yeah dude just get molested by iranian president LOL!!!!
