### ISSUE TITLE
There should be a warning upon starting the launcher for the very first time

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/SS14.Launcher#159]
It should say something like "all servers on the hub are community servers not hosted by us" or something similar, it would help the PCTide understand that getting banned from one server doesn't mean that the whole game sucks or w/e

**Comment by VasilisThePikachu** [comment]
> It should say something like "all servers on the hub are community servers not hosted by us" or something similar, it would help the PCTide understand that getting banned from one server doesn't mean that the whole game sucks or w/e

There already is, but its for an "early access" message

**Comment by PJB3005** [comment]
Tide over back to your desks
