### ISSUE TITLE
Connecting popup can be created out of your screen's bounds

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/SS14.Launcher#17]
...if you move the launcher near the top of your screen and connect to a server.
(screenshot taken at max screen height)
![image](https://user-images.githubusercontent.com/6766154/96888903-62299e80-1486-11eb-99c1-464c1436957d.png)

**Comment by PJB3005** [comment]
Connecting popup has been replaced with an overlay over the launcher window.
