### ISSUE TITLE
Need some system to enable Server GC for large replays

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/SS14.Launcher#177]

**Comment by VasilisThePikachu** [comment]
How big should a replay be until server gc is enabled?

**Comment by PJB3005** [comment]
> How big should a replay be until server gc is enabled?

Should probably be server config but I'd wager anything past 100 MB?

**Comment by VasilisThePikachu** [comment]
> > How big should a replay be until server gc is enabled?
> 
> Should probably be server config but I'd wager anything past 100 MB?

So should a server get to decide to add servergc to their replays? Most replays are over 100mb so you may as well enable it for all (well all over 100mb) instead of relying on the server operator

**Comment by PJB3005** [comment]
> So should a server get to decide to add servergc to their replays?

Yes IMO. Should be a flag in the metadata somehow.

> Most replays are over 100mb so you may as well enable it for all 

Replays are implemented as a general purpose system as *content bundles*, forcibly making every content bundle server GC wouldn't make much sense.
