### ISSUE TITLE
Spamming refresh on the launcher's server list crashes it.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/SS14.Launcher#18]
![2020-12-07_18-43-57](https://user-images.githubusercontent.com/49448379/101431806-84c12b00-38ff-11eb-9030-f4f3aa6a0a33.gif)

Think it might be caused by calling a refresh while the list is still populating.

**Comment by PJB3005** [comment]
I can't seem to reproduce this locally. What's the error that gets thrown to the console?

**Comment by SweptWasTaken** [comment]
> 
> 
> I can't seem to reproduce this locally. What's the error that gets thrown to the console?

I just reproduced it on Windows 10.

https://user-images.githubusercontent.com/49448379/140628593-eeb7bb91-d577-4f33-bdf6-2d918210bbb4.mp4

**Comment by PJB3005** [comment]
I didn't push an update to the launcher yet with the fix.

**Comment by SweptWasTaken** [comment]
> 
> 
> I didn't push an update to the launcher yet with the fix.

Ok
