### ISSUE TITLE
Build 0.30 for MacOS is broken

### ISSUE THREAD

**Issue by RomanDronow** [space-wizards/SS14.Launcher#197]
`Space Station 14 Launcher.app/Contents/MacOS/../Resources/bin/SS14.Launcher: No such file or directory`

I believe there is some files missing in appication bundle

**Comment by PJB3005** [comment]
God damnit.

**Comment by PJB3005** [comment]
just to confirm: is this via Steam or via the website download?

**Comment by RomanDronow** [comment]
From the website, yes. It is also 15 megabytes less in size that 0.29.1 on github assets

**Comment by PJB3005** [comment]
New version has been published, should fix it, thanks for the quick report.
