### ISSUE TITLE
Please consider providing a tar(.gz/.bz2/etc.) archive for Linux

### ISSUE THREAD

**Issue by atleta** [space-wizards/SS14.Launcher#25]
## Description
The linux launcher comes in a zip file but zip does not store the file permissions/attributes and thus after unpacking the game won't work. There are 2 (maybe 3) files that need to be executable:
- `bin/SS14.Launcher` - started by the shell script `SS14.Launcher`
- `bin/loader/SS14.Loader`
- probably `SS14.Launcher` as well (though it's not 100% mandatory, it's easier for the users to figure out if it is)

**Additional context**

After making `bin/SS14.Launcher` executable and starting the app, it failed with an exception that was apparently fixed by making `bin/loader/SS14.Loader` executable too.

```
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
```

**Comment by atleta** [comment]
I've used mc to unpack it. With Info-ZIP's unzip it does work. With tar, available on all linux systems it would always work :).

**Comment by atleta** [comment]
Meh... It's a problem that I ran into as a user and reported thinking that you are interested in provding an as frictionless as possible experience to your users. There is an obvious and ismple solution, but of course you can point to mc (and maybe some other project) as well. Yes, if they fix it then your problem will go away. Good luck.

**Comment by mirrorcult** [comment]
average HN user lol

**Comment by moonheart08** [comment]
> Meh... It's a problem that I ran into as a user and reported thinking that you are interested in provding an as frictionless as possible experience to your users. There is an obvious and ismple solution, but of course you can point to mc (and maybe some other project) as well. Yes, if they fix it then your problem will go away. Good luck.

It's likely to be fixed, but it's basically bottom priority as we've never had this complaint before over quite a long time, and it seems tied to a specific program that's pretty niche.

**Comment by atleta** [comment]
> average HN user lol

I spent my time to provide feedback on an issue I've found piece of open source software that I've tried once for 5 minutes. Because I think that is the right thing to do. Not a lot of help, but some help. Most (would be) users won't tell you if your thing doesn't work for them, just go away. Maybe your project is different, maybe your target audience is different. I have no idea. But I don't think that ignorance is a good or even an acceptable response to someone politly offering help. Even if it took them just 5 minutes.

And now I took the time to explain why you were wrong instead of just calling you an idiot. I'm out. Unsubscribed.

**Comment by mirrorcult** [comment]
Oh my Fucking god he unsubscribed

**Comment by DogZeroX** [comment]
![image0](https://user-images.githubusercontent.com/43253663/140417566-ff985daf-c796-47ab-a852-03027ed49b64.gif)

**Comment by ZeroDayDaemon** [comment]
![Monkey](https://user-images.githubusercontent.com/60460608/140417680-f7cf0b05-2d4f-488d-b07b-31fa145ae415.jpg)

**Comment by Visne** [comment]
For anyone reading in the future, from the Midnight Commander uzip README:

> Known problems and Unsupported features
=======================================
>
> [...]
>
> Extracted files do not have the same modification/access date as
in the archive. The same applies for permissions and ownership.
Fortunately MC extfs will set these attributes based on the file
listings.
