### ISSUE TITLE
Join Waitlisting Support

### ISSUE THREAD

**Issue by Efruit** [space-wizards/SS14.Launcher#33]
Some launchers (Steam/Source comes to mind) allow you to join a full server as soon as it advertises capacity.

The Steam/Source implementation is one-way only: the server only publishes its player cap and current player count, and clients poll it to see if any slots are open. If the player count drops below the cap, the launcher attempts to join.

Of course, this leads to a window of time when multiple clients will be attempting to join, with potentially too few slots to accommodate them all. This could be improved upon by issuing join tickets and queuing them, or raffling them off whenever slots are opened.

```
Launcher     Client     Server
    |-----------+-------->|     Join?
    |<----------+---------|     Full. Ticket is 123456. Expires in 30s.
    |           |         |
    |           |         |     (Time passes)
    |           |         |
    |-----------+-------->|     Join? Ticket 123456.
    |<----------+---------|     Full. Ticket kept alive. Expires in 30s.
    |           |         |
    |           |         |     (Time passes)
    |           |         |
    |-----------+-------->|     Join? Ticket 123456.
    |<----------+---------|     Slot reservation open. Expires in 60s.
    |-----------+-------->|     ACK. Launching client.
    |           |         |
    |---------->|         |     ./Content.Client --autoconnect wherever --ticket 123456
    |           |-------->|     Join. Ticket is 123456.
    |           |<--------|     Welcome aboard.
```

If raffling is preferred, the flow could instead include a list of ticket hashes that may join.

```
Launcher     Client     Server
    |-----------+-------->|     Join?
    |<----------+---------|     Full. Open tickets are sha1(123451), sha1(123452), sha1(123453).
    |-----------+-------->|     Request Ticket?
    |<----------+---------|     Ticket is 123456.
    |           |         |
    |           |         |     (Time passes)
    |           |         |
    |-----------+-------->|     Join?
    |<----------+---------|     Full. Open tickets are sha1(123453), sha1(123454), sha1(123455).
    |           |         |
    |           |         |     (Time passes)
    |           |         |
    |-----------+-------->|     Join?
    |<----------+---------|     Full. Open tickets are sha1(123456), sha1(123457), sha1(123458).
    |           |         |
    |---------->|         |     ./Content.Client --autoconnect wherever --ticket 123456
    |           |-------->|     Join. Ticket is 123456.
    |           |<--------|     Welcome aboard.
```

Of course, this could also be accomplished through auth/hub, but that's unneeded centralization.

**Comment by Efruit** [comment]
I'm not sure how it'd work if a client disconnects unexpectedly. Should the server immediately raffle off their slot, or have a grace period for reconnecting?

**Comment by Visne** [comment]
Old issue, but I'm pretty sure the stance is that waitlisting won't be implemented to encourage people to join smaller servers. That would more equally spread out players instead of possibly creating massive queues.

**Comment by Subversionary** [comment]
> Old issue, but I'm pretty sure the stance is that waitlisting won't be implemented to encourage people to join smaller servers. That would more equally spread out players instead of possibly creating massive queues.

Holy necro, this wont be possible to do from the launcher anyway as the time from starting the game to taking the slot is rather long for this task.
