### ISSUE TITLE
Explicitly verify for settings.db corruption on startup.

### ISSUE THREAD

**Issue by wrexbe** [space-wizards/SS14.Launcher#34]
A user had this file get messed up, and the launcher crashes.
Easiest way to reproduce:
Open launcher_config.json
Save the file with nothing in it.
Start the launcher

**Comment by PJB3005** [comment]
I actually moved launcher master to an SQLite database for config. It should be less prone to any sort of corruption errors and easier to check integrity of.

**Comment by Visne** [comment]
Is this still something we want? How would integrity be checked?

**Comment by PJB3005** [comment]
You could run an [integrity check](https://www.sqlite.org/pragma.html#pragma_integrity_check) with SQLite if you want to be really thorough. Would probably not want to run it on the Content DB on startup though as that'd be too slow.

I'm not really sure it's too necessary however. SQLite is really robust, so.

**Comment by Visne** [comment]
I think we can just close this then, it's not like the DB stores mission critical stuff anyways and it becoming corrupt is unlikely too. I can understand this issue being created back when we were using JSON but that's not relevant anymore.
