### ISSUE TITLE
Auto-Selection & Server "Groups"

### ISSUE THREAD

**Issue by Efruit** [space-wizards/SS14.Launcher#35]
We should move away from displaying individual servers (by default) in favor of selecting servers automatically from a group.

For example, the official "group" would be the four mainline Wizard's Den servers (currently _Miros_, _Spider_, _Lizard_, and _Centipede_).

## Auto-Selection Strategies
Plenty of ways to go about this.
Off the top of my head:
 - Lowest-population first (makes for better distribution across all servers)
 - Highest-population first (improves round player count)
 - Ping-weighted
 - Starting first (servers in the lobby state get picked first)
 - Piecewise population i.e. bonus for pop. < ~50% capacity, penalty for pop. > ~50% capacity (50% high-water mark is arbitrary)
 - Server delegated (server advertises a weight in its metadata)
 - Most admins online
 - Random
 - ...or a mix of any of the above

If we wanted to be fancy, we could add sliders for each factor and let the player tweak the weights.

**Comment by Efruit** [comment]
Fine, but the motivating problem still remains:

How do we spread the population out so that it's not 100% of the playerbase on one server (until it's full)?

**Comment by PJB3005** [comment]
If you want less people on one server, then you should petition to reduce the player cap on our servers.

**Comment by Efruit** [comment]
@PJB3005 That's a bullshit answer and we both know it.

Players who start the launcher are trying to play a multiplayer game. If they can't join one, they'll play something else.

**Comment by PJB3005** [comment]
So you want more servers then *and* reduced playercount per server.

**Comment by Efruit** [comment]
No, I want players to join servers in a roughly even distribution which also factors in round status, player count, ping, and whatever else I put in the issue description.

Since they won't do it themselves, we need to make it happen. And, once that's done, we need to make it easier than joining a server normally, otherwise people won't use it.

And knock it off with the bad-faith arguing.

**Comment by PJB3005** [comment]
We're not discussing this here.
