### ISSUE TITLE
Blocking connection to favorited servers with no status is cringe

### ISSUE THREAD

**Issue by ike709** [space-wizards/SS14.Launcher#43]
Right now I'm messing around with a production OD test server, and I have to Direct Connect every time because when I favorited it it's `Unable to connect` because it isn't configured to report its status.

Instead of disabling `Connect`, just make it red or give a notice popup or something.

**Comment by PJB3005** [comment]
As discussed on Discord there is something very wrong with the game server if it doesn't return functional `/status` but *does* return functional `/info`. I don't feel this is worth supporting a workaround to a broken server like that.
