### ISSUE TITLE
Clearing installations should show a prompt

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/SS14.Launcher#51]
A few people have just assumed it did nothing and didn't realise it fixed their issue.

**Comment by PJB3005** [comment]
I guess? Fancy would be to add some sort of popup notification that doesn't claim the whole window, but then you have to figure *that* out.

**Comment by Visne** [comment]
Well I figured it could also be possible to just change the button text to "Done!" for 2 seconds, which would make it pretty clear that pressing the button did something.

**Comment by PJB3005** [comment]
That's probably the easiest solution, yes.
