### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by BozoDel** [space-wizards/SS14.Launcher#55]
The launcher told me it was too old, and I had to download a new one, which I did. Now I get different errors when trying to connect to different servers.

Lizard and Spider give me this:
> There was an error while downloading server content. Please ask on Discord for support if the problem persists.

Outer Rim 14 hangs in a screen that reads:
> Updating: Storing assets in database...

Miros takes forever to download, then crashes with a floating point exception.

Someone in the forums seemed to have the same issue a couple of weeks ago and someone else said there was a patch on Discord.
https://forum.spacestation14.io/index.php?/topic/538-help/#comment-2038

I'm asking here cause this seems like the proper place. I'm not very excited about having to join yet another walled garden... but I'll do it if I have to.

**Comment by metalgearsloth** [comment]
> I could send you and/or another dev via forum PM. What should I send? Just the regular output, or should I set some logging options?
> 
> EDIT: can also use spacestation14.io's contact e-mail, herp derp

Send it to me on the forum and I'll dump it in discord.

**Comment by PJB3005** [comment]
95% chance it's just the zstd thing though.

**Comment by BozoDel** [comment]
It seems fixed!

**Comment by zetrez** [comment]
Сan u told me how u fix this problem?  I can't find a solution anywhere

**Comment by BozoDel** [comment]
The issue I had was a year and a half ago, and it was fixed by an update. If you're having trouble now, it must be a different issue. You might wanna make a new bug report.

Also, I made my report here in the Launcher repository, but I still don't know if that was the right place. Good luck!
