### ISSUE TITLE
UI does not repaint if obscured and unobscured

### ISSUE THREAD

**Issue by SpaceManiac** [space-wizards/SS14.Launcher#6]
If the launcher is totally hidden from view, when it is returned to view its display is blank or junk until the mouse is moved in such a way that the UI must repaint.

OS: Linux

**Comment by PJB3005** [comment]
It's an Avalonia bug, probably.

**Comment by Visne** [comment]
Still an issue in 2024?

**Comment by SpaceManiac** [comment]
No longer reproduces for me, but I do not know whether SS14 updates fixed it or changes to my system fixed it.

**Comment by Visne** [comment]
We're probably a few Avalonia versions along as well, so I'll just assume this is closed (but feel free to reopen if required)
