### ISSUE TITLE
System.InvalidOperationException preventing the Launcher from starting.

### ISSUE THREAD

**Issue by LeonWilzer** [space-wizards/SS14.Launcher#62]
I installed the game using Steam, and it didn't start. When I launch it through the terminal I receive the mentioned unhandled exception, after some normal messages:

Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.

I am on Arch Linux and I looked up the issue and after skimming a few GitHub issues, it seems possibly related to Avalonia and me maybe missing some fonts or similar, which makes sense, given the error message. The issue-threads would usually recommend installing mscorefonts and trying to launch the applications with LC_ALL=C,
but neither changed the result.

I can provide you with system specs and the terminal output, if needed.

**Comment by PJB3005** [comment]
Could I get a full log with stack trace?

**Comment by LeonWilzer** [comment]
I am terribly sorry for responding late, but below is the terminal output of the launcher.
[log.txt](https://github.com/space-wizards/SS14.Launcher/files/8778476/log.txt)

**Comment by PJB3005** [comment]
Now that is interesting. Seems like a bug in Avalonia?

**Comment by PJB3005** [comment]
No idea, sorry.

**Comment by wrexbe** [comment]
Try installing the Microsoft fonts.
https://wiki.archlinux.org/title/Microsoft_fonts

I found a similar issue on the Avalonia github, and that was the recommended solution
https://github.com/AvaloniaUI/Avalonia/issues/5774

**Comment by PJB3005** [comment]
Well I really wish that wasn't the required solution, but apparently it's a Skia bug so 🤷.

**Comment by LeonWilzer** [comment]
> Try installing the Microsoft fonts. https://wiki.archlinux.org/title/Microsoft_fonts
> 
> I found a similar issue on the Avalonia github, and that was the recommended solution [AvaloniaUI/Avalonia#5774](https://github.com/AvaloniaUI/Avalonia/issues/5774)

 Well, I tried installing the Win10 one from the AUR, but the installation failed. So I installed the Win11 font, which was successful, but still crashes when starting the Launcher. Another note, Steam updated the game, but that changed nothing. So I guess there is nothing to do, until the issue is resolved. :man_shrugging:
Thank you for your time.

**Comment by Visne** [comment]
Pretty sure this is the same issue as #84. If this is still affecting you, can you install `ttf-dejavu` and see if it is fixed then? If not, I would like to know too.

**Comment by LeonWilzer** [comment]
Well, it seems to work now, regardless whether Dejavu is installed or not. I am closing the issue now.
