### ISSUE TITLE
Infer language filter doesn't seem to work for Delta-V

### ISSUE THREAD

**Issue by Skyedra** [space-wizards/SS14.Launcher#89]
It seems the infer for Delta-V server does not pick up language filter, though does pick up MRP filter:

![image](https://github.com/space-wizards/SS14.Launcher/assets/22365940/38913ba0-f810-427b-a44b-bfa15c5bf07e)

![image](https://github.com/space-wizards/SS14.Launcher/assets/22365940/b5d826e1-cc4c-43b1-8e84-693204453b96)

**Comment by moonheart08** [comment]
Delta-V should just explicitly specify tags instead.

**Comment by PJB3005** [comment]
Delta-V got updated and specifies `lang:en-US` now. Something is broken about that.

**Comment by Skyedra** [comment]
Thanks for fix :+1:
