### ISSUE TITLE
Info on how big the download is when joining a server

### ISSUE THREAD

**Issue by fiercestwarrior** [space-wizards/SS14.Launcher#9]
![image](https://user-images.githubusercontent.com/52793290/86066238-8a216c00-ba69-11ea-8ed0-a6cf976e41f4.png)
i wanna know how many bytes im downloadin bro....

**Comment by PJB3005** [comment]
The launcher has been reporting this ever since v0.3.5. Are you on an old version?

**Comment by partyaddict** [comment]
0.3.8, aka latest

**Comment by partyaddict** [comment]
redownloaded just to stay safe and i see nothing

**Comment by ShadowCommander** [comment]
Shows for me when joining a server.
![Capture](https://user-images.githubusercontent.com/10494922/87222389-119f9280-c328-11ea-821c-663606ce1760.PNG)

**Comment by partyaddict** [comment]
I play on Windows 7 if that means anything

**Comment by TheChosenEvilOne** [comment]
![484333054119116800](https://user-images.githubusercontent.com/34602646/87222680-771e6e00-c37e-11ea-9d3d-75a0e748c8f9.png)
but really, it works fine on windows 7 for me. Are you sure you actually ran the correct launcher version?
![image](https://user-images.githubusercontent.com/34602646/87222737-12afde80-c37f-11ea-809f-b57dd0132791.png)

**Comment by PJB3005** [comment]
In your initial screenshot the dialog is still in "indeterminate" mode because the server hasn't responded with a file length yet. Does it happen all the way through the downloads @partyaddict?

**Comment by partyaddict** [comment]
yes

**Comment by PJB3005** [comment]
I'm just gonna close this. The issue long predates the new manifest download system so it's probably not relevant anymore.
